# This file is used to configure your project.
# Read more about the various options under:
# http://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

[metadata]
name = ncmw
description = This is a workflow for investigating metabolic community models on a nasal medium.
author = manuelgloeckler
author_email = manuel.gloeckler@student.uni-tuebingen.de
license = MIT
long_description = file: README.md
project_urls =
    Documentation = https://google.com

platforms = any

classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python


[options]
zip_safe = False
packages = ncmw
include_package_data = True

python_requires = >=3.13

# Project (runtime) dependencies ONLY
install_requires =
    numpy>=2.1
    pandas>=2.2
    scipy>=1.14
    cobra>=0.29
    hydra-core>=1.3
    omegaconf>=2.3
    networkx>=3.2
    matplotlib>=3.9
    setuptools>=70
    mip
    torch
    seaborn
    memote==0.13.0
    matplotlib-venn


[options.packages.find]
where = ncmw
exclude =
    tests


[options.extras_require]
# Optional feature sets (install only if needed)

plot =
    seaborn
    matplotlib-venn

opt =
    torch
    swiglpk
    memote==0.13.0
    mip
    cplex

# Tests
testing =
    pytest
    pytest-cov
    pytest-xdist

# Docs
docs =
    sphinx
    myst-parser
    sphinx-rtd-theme
    sphinx-autodoc-typehints

# Common "developer workstation" bundle
dev =
    black
    ruff
    isort
    flake8
    mypy
    types-PyYAML
    pre-commit
    build
    twine
    wheel
    ipykernel
    jupyterlab
    notebook
    pytest
    pytest-cov
    pytest-xdist
    sphinx
    myst-parser
    sphinx-rtd-theme
    sphinx-autodoc-typehints


[options.entry_points]
console_scripts =
    ncmw = ncmw.scripts.ncmw_scripts:run_ncmw
    ncmw_setup = ncmw.scripts.setup_scripts:run_setup_hydra
    ncmw_analysis = ncmw.scripts.analysis_scripts:run_analysis_hydra
    ncmw_community = ncmw.scripts.community_scripts:run_community_hydra
    ncmw_host = ncmw.scripts.host_scripts:run_host_hydra


[tool:pytest]
addopts =
    --cov ncmw --cov-report term-missing
    --verbose
norecursedirs =
    dist
    build
    .tox
testpaths = tests


[bdist_wheel]
universal = 1


[devpi:upload]
no_vcs = 1
formats = bdist_wheel


[flake8]
max_line_length = 88
extend_ignore = E203, W503
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py


[pyscaffold]
version = 4.0.2
package = ncmw
extensions =
